title: Onur Akcakaya # your name (or website title) here
logo: "/images/Onur Akcakaya.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | SQL | Tableau | Excel | Data Visualization | Python | Salesforce Certified Admin 
  <br><br>
  <a href="https://www.linkedin.com/in/onurakcakaya/" target="_blank">View My LinkedIn Profile</a>
  <br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
